# 1. SwiftLint Rules: https://realm.github.io/SwiftLint/rule-directory.html
# 2. Validate this file's YML format: https://yamlchecker.com/

# paths to include during linting
included:
  - TMSDKDemoIntegration

# paths to ignore during linting (takes precedence over `included`)
excluded:
  - release

# reporter output format
reporter: "xcode"

# rule identifiers to exclude from running
disabled_rules:
  - file_length
  - line_length
  - type_body_length
  - function_parameter_count
  - redundant_string_enum_value
  - nesting
  - multiple_closures_with_trailing_closure
  - unused_closure_parameter
  - comment_spacing
  - todo
  - inclusive_language
  - force_try
  - force_cast

# adjust rule settings
type_name:
  min_length: 2
  max_length: 50
  allowed_symbols: ["_"]

function_body_length:
  warning: 300

cyclomatic_complexity:
  warning: 15
  error: 20
  ignores_case_statements: true

vertical_whitespace:
  max_empty_lines: 3

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

identifier_name:
  min_length: 2
  max_length:
    warning: 90
    error: 1000
  excluded: # excluded via string array
    - id
    - URL
  allowed_symbols: ["_"]
  validates_start_with_lowercase: warning

